"""
Django settings for ucsg_caces project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o)+x+lyi@w=fyp-hl@n8*90af)vrwwx0=+!3orul@2&jh$mta0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'seguimiento_syllabus',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Mientras desarrollas el frontend React por separado (ej. npm run dev en :5173),
# esto permite que te hable a la API sin bloqueos de CORS.
# En producción, mejor especificar el dominio exacto en vez de allow all.
CORS_ALLOW_ALL_ORIGINS = DEBUG

# Forzamos que la API SIEMPRE responda en JSON (nunca en HTML "navegable"),
# así evitamos el error TemplateDoesNotExist al abrir una URL de /api/ desde
# el navegador, y el frontend React siempre recibe lo que espera.
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
}

ROOT_URLCONF = 'ucsg_caces.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ucsg_caces.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='ucsg_caces_db'),
        'USER': config('DB_USER', default='ucsg_user'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='3306'),
        'OPTIONS': {
            # utf8mb4 soporta emojis/tildes/ñ sin problemas y es el
            # estándar recomendado por Django para MySQL 8.
            'charset': 'utf8mb4',
        },
    }
}

# Integración de evidencias con OneDrive (Microsoft Graph API, app-only /
# client-credentials vía MSAL). Ver seguimiento_syllabus/onedrive_service.py.
# Credenciales de Azure AD: tenant de prueba "Microsoft 365 Apps for
# business" (trial, vence 12/8/2026 — renovar o migrar a tenant
# institucional de la UCSG antes de esa fecha o se corta la subida).
# Default vacío a propósito: sin estas 4 variables en .env,
# subir_a_onedrive() falla con un error explícito
# (OneDriveNoConfiguradoError) en vez de un traceback genérico.
AZURE_TENANT_ID = config('AZURE_TENANT_ID', default='')
AZURE_CLIENT_ID = config('AZURE_CLIENT_ID', default='')
AZURE_CLIENT_SECRET = config('AZURE_CLIENT_SECRET', default='')
ONEDRIVE_DRIVE_ID = config('ONEDRIVE_DRIVE_ID', default='')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')