# Generated by Django 5.2.15 on 2026-06-25 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cohorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('malla', 'Malla Curricular'), ('syllabus', 'Syllabus'), ('acta', 'Acta de Retroalimentación')], max_length=20)),
                ('archivo', models.FileField(upload_to='evidencias/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento_syllabus.cohorte')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_si', models.IntegerField(default=0)),
                ('respuesta_no', models.IntegerField(default=0)),
                ('cohorte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento_syllabus.cohorte')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento_syllabus.preguntaencuesta')),
            ],
        ),
    ]
