# Generated by Django 5.2.15 on 2026-07-04 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_syllabus', '0005_migrar_periodos_y_evidencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(upload_to='evidencias/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'mp4'])]),
        ),
    ]
