# Generated by Django 6.0.6 on 2026-07-08 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_syllabus', '0007_normalizar_evidencia_reglamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='periodo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='seguimiento_syllabus.periodoacademico'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='seguimiento_syllabus.asignatura'),
        ),
    ]