# Generated by Django 4.2.30 on 2026-07-12 22:29
#
# Paso 1 de 2 de la integración con OneDrive (ver prompt_onedrive.md):
# agrega los campos nuevos (onedrive_url, onedrive_item_id,
# nombre_archivo_original) y hace `archivo` nullable/blank para no romper
# evidencias históricas ya guardadas localmente. El paso 2 (sacar `archivo`
# del modelo) se hace en una migración aparte, más adelante, una vez
# confirmado con `migrar_evidencia_a_onedrive.py --aplicar` que toda la
# evidencia histórica ya se subió a OneDrive.

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento_syllabus', '0010_cohorte_carrera_obligatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='nombre_archivo_original',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='onedrive_item_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='evidencia',
            name='onedrive_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='evidencias/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'mp4'])]),
        ),
    ]